#
# usage: ansible-playbook -i steam.inv
#
# games:  list of games to be installed
#

---

- name: Install Steam Server
  hosts: "*steam-servers"
  user: root

  vars:
    test_var: 42
    games_dict:
      squad: 403240
      hellion: 598850
      7days: 294420

  tasks:

    # verify base packages are installed
#    - include:

    - name: install necessary packages
      yum:
        name: "{{ item }}"
        state: installed
      with_items:
        - glibc.i686
        - libgcc.i686

    # create steam user
    - name: Create steam user
      user:
        name: steam
        state: present

    # create steam dir
    - name: Create steam directory
      file:
        path: /home/steam/steam
        state: directory
        mode: 0755

    # get steam binaries
    - name: Download steam binaries
      shell: cd /home/steam/steam; wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz;

    # update perms on file
    - name: Set permissions on steam package
      file:
        path: /home/steam/steam/steamcmd_linux.tar.gz
        owner: steam

    # unpackage steam files
    - name: Unpackage steam files
      shell: cd /home/steam/steam; tar xvf steamcmd_linux.tar.gz

    # install steam games
#    - debug: msg="Install Steam App ID {{ games_dict[item] }}"
#      when: games is defined
#      with_items: "{{ games.split(',') }}"