# usage: ansible-playbook -i steam.inv deploy-steamcmd.yaml \
#        -e "games=squad,7days" --limit 'dev-steam-servers'
#
# games: If left empty, this just installs steamcmd. Otherwise, provide a 
#        comma separated list of games defined in the games_dict below.
#
#

---

- name: Install SteamCmd
  hosts: "*steam-servers"
  user: root

  tasks:

    # verify base packages are installed
    - include: install-base-packages.yaml

    - name: Install necessary packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - lib32gcc1

    # create steam user
    - name: Create steam user
      user:
        name: steam
        state: present

    # create steam dir
    - name: Create steamcmd directory
      file:
        path: /home/steam/steamcmd
        state: directory
        owner: steam
        group: steam
        mode: 0755

    # get steam binaries
    - name: Download steamcmd package
      shell: cd /home/steam/steamcmd; wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz;

    # update perms on file
    - name: Set permissions on steamcmd package
      file:
        path: /home/steam/steamcmd/steamcmd_linux.tar.gz
        owner: steam

    # unpackage steam files
    - name: Unpackage steamcmd files
      shell: cd /home/steam/steamcmd; tar xvf steamcmd_linux.tar.gz

    # set permissions on steam files
    - name: Set permissions on steamcmd files
      file:
        path: /home/steam/steamcmd
        state: directory
        owner: steam
        group: steam
        recurse: yes

- include: install-steam-games.yaml
  when: games is defined
